# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9669fb8d8e01b8006927d37b8d0656b519e7d6bee4ac4f4fd5fb093820e809c530ef2cf44f77f426745df082d98a1518ecb1d2eec32bd2a0d60902e9dc1d750d

test:
  secret_key_base: f8c790271d47848023381f77ba186c9232ce30178d1a71cf768f2bcd537de1432c67dbda002d0c5425e87886d5c7975e1db5b68b919098bd7f14af1ea61e65f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
